### PR TITLE
Add Sauer Pai struct

### PR DESCRIPTION
**Pull request by marenat**

### CODE REVIEW

**Review by rodrigomha — CHANGES_REQUESTED** [review]
You need to run the generate structs. To do so in your PowerSystems folder and project run the following:

```
using InfrastructureSystems
InfrastructureSystems.generate_structs("./src/descriptors/power_system_structs.json", "./src/models/generated")
```

**Review by rodrigomha — APPROVED** [review]
Looks good. The PSID error is something that we are fixing it there and is not related with this PR.

**Comment by jd-lara** [comment]
@marenat This PR is missing the tests for the new struct that it can be added to a system

**Comment by rodrigomha** [comment]
A better example would be this one:

https://github.com/NREL-SIIP/PowerSystems.jl/blob/1020c4ae5322fe088358d2e544152b375acc19e6/test/test_dynamic_generator.jl#L49

You can add the SauerPai model in that test set

**Review by rodrigomha — APPROVED** [review]
With the additional test LGTM

**Pull request merged**
