### PR TITLE
add Grid Following structs

### PR DESCRIPTION
**Pull request by rodrigomha**
The following PR add three structs to be used for a Grid Following inverter implementation in PowerSimulationsDynamics.jl

To do:
- [x] Need some discussion on names on both PLL and Outer Controllers.
- [x] Tests

### CODE REVIEW

**Comment by jd-lara** [comment]
The tests for the autogenerated functions should be tested here automatically https://github.com/NREL-SIIP/PowerSystems.jl/blob/3525ca87c8bde120649bb9aac52369a5296a2f75/test/test_powersystemconstructors.jl#L93 check if the call to `IS.get_all_concrete_subtypes(DynamicComponent)` is returning the new components you are adding.

**Comment by daniel-thom** [comment]
> The tests for the autogenerated functions should be tested here automatically
> 
> https://github.com/NREL-SIIP/PowerSystems.jl/blob/3525ca87c8bde120649bb9aac52369a5296a2f75/test/test_powersystemconstructors.jl#L93
> 
> check if the call to `IS.get_all_concrete_subtypes(DynamicComponent)` is returning the new components you are adding.

Subtypes of ActivePowerControl and ReactivePowerControl do not have their accessors tested automatically.

**Comment by jd-lara** [comment]
> > The tests for the autogenerated functions should be tested here automatically
> > https://github.com/NREL-SIIP/PowerSystems.jl/blob/3525ca87c8bde120649bb9aac52369a5296a2f75/test/test_powersystemconstructors.jl#L93
> > 
> > check if the call to `IS.get_all_concrete_subtypes(DynamicComponent)` is returning the new components you are adding.
> 
> Subtypes of ActivePowerControl and ReactivePowerControl do not have their accessors tested automatically.

You can add it here 

https://github.com/NREL-SIIP/PowerSystems.jl/blob/bf102c4751c242a9fe0610fad805e77e9644768d/test/test_powersystemconstructors.jl#L103

**Comment by rodrigomha** [comment]
> > > The tests for the autogenerated functions should be tested here automatically
> > > https://github.com/NREL-SIIP/PowerSystems.jl/blob/3525ca87c8bde120649bb9aac52369a5296a2f75/test/test_powersystemconstructors.jl#L93
> > > 
> > > check if the call to `IS.get_all_concrete_subtypes(DynamicComponent)` is returning the new components you are adding.
> > 
> > 
> > Subtypes of ActivePowerControl and ReactivePowerControl do not have their accessors tested automatically.
> 
> You can add it here
> 
> https://github.com/NREL-SIIP/PowerSystems.jl/blob/bf102c4751c242a9fe0610fad805e77e9644768d/test/test_powersystemconstructors.jl#L103

Added!

**Review by jd-lara — APPROVED** [review]
Great contribution. Thanks!

**Pull request merged**
